-- AlterTable
ALTER TABLE "activity-score" ADD COLUMN     "endorsement" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "endorserLevelBonus" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "follower" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "popularityCap" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN     "verifiedVolunteerHour" DOUBLE PRECISION NOT NULL DEFAULT 2;
